"""add: collection code column

Revision ID: 21d5c1b04df7
Revises: 686d9f737e0c
Create Date: 2025-12-22 00:46:58.460896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d5c1b04df7'
down_revision: Union[str, Sequence[str], None] = '686d9f737e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('embedding_store_collection_code_key'), 'embedding_store', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('embedding_store_collection_code_key'), 'embedding_store', ['collection_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
