"""add: collection code column

Revision ID: 686d9f737e0c
Revises: a5c5848e0b0e
Create Date: 2025-12-22 00:33:37.164383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '686d9f737e0c'
down_revision: Union[str, Sequence[str], None] = 'a5c5848e0b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding_store', sa.Column('collection_code', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'embedding_store', ['collection_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'embedding_store', type_='unique')
    op.drop_column('embedding_store', 'collection_code')
    # ### end Alembic commands ###
